### PR TITLE
feat: EnableJsonLayout for using NLog Layout for generating document

### PR DESCRIPTION
**Pull request by snakefoot**
Now you can do this:

```
<extensions>
    <add assembly="NLog.Targets.ElasticSearch"/>
    <add assembly="Elastic.CommonSchema.NLog"/>
</extensions>
<targets>
   <target xsi:type="ElasticSearch" enableJsonLayout="true">
       <layout xsi:type="EcsLayout" />
   </target>
</targets>
```

Resolving #122 

#### Checklist
- [x] My commits follow [Conventional Commits](https://www.conventionalcommits.org)
- [ ] documentation is updated

### CODE REVIEW

**Comment by johnjaylward** [comment]
Is there a pre-release where I can test this out?

**Comment by snakefoot** [comment]
@johnjaylward You can download the nuget-package here:

https://ci.appveyor.com/project/markmcdowell/nlog-targets-elasticsearch/builds/32860944/artifacts

Just place it in local-nuget-package-path, and then you can try it out. Would be nice with some feedback

**Comment by johnjaylward** [comment]
Thanks @snakefoot , I tried it out, but I get an exception thrown from the Logger.

```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Program' threw an exception.
  Source=Program
  StackTrace:
   at Program.<Main>d__7.MoveNext() in ....\Program.cs:line 34

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
NLogConfigurationException: Exception when parsing ....\bin\Debug\netcoreapp3.1\NLog.config. 

Inner Exception 2:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 3:
ArgumentException: LayoutRenderer cannot be found: 'ElasticApmTraceId'

```

Config:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      throwExceptions="true" >
<extensions>
  <add assembly="NLog.Targets.ElasticSearch"/>
  <add assembly="Elastic.CommonSchema.NLog"/>
</extensions>
  <targets>
    <target type="ColoredConsole"
            name="console"
            encoding="UTF-8"
            layout="${longdate} ${level:uppercase=true} Thread(${threadid}:${threadname}) ${callsite}:${callsite-linenumber} - ${message} ${exception:format=tostring}"
            useDefaultRowHighlightingRules="true"
            errorStream="false"
            detectConsoleAvailable="false" />
    <!-- Use a buffered wrapper, or other async target for any network pushed logs like Elastic or SQL -->
    <target type="ElasticSearch"
            name="elastic"
            uri="http://localhost:9200"
            requireAuth="false"
            username=""
            password=""
            index="appdevlogs-dev-${date:format=yyyy.MM.dd}"
            documentType="logevent"
            includeAllProperties="false"
            excludedProperties=""
            maxRecursionLimit="1"
            disableAutomaticProxyDetection="true"
            disablePing="false"
            EnableHttpCompression="false"
            DisableCertificateValidation="false"
            enableJsonLayout="true"
    >
      <layout type="EcsLayout" />
    </target>
  </targets>
  <rules>
    <logger name="*" minlevel="Trace" writeTo="console" />
    <logger name="*" minlevel="Trace" writeTo="elastic" />
  </rules>
</nlog>
```

Dependencies:
```xml
  <ItemGroup>
    <PackageReference Include="NLog" Version="4.7.2" />
    <PackageReference Include="NLog.Targets.ElasticSearch" Version="7.1.14-alpha-lgtulitr" />
    <PackageReference Include="Elastic.CommonSchema.NLog" Version="1.5.0" />
  </ItemGroup>
```

Is there another dependency I should have for the renderer that isn't found?

**Comment by johnjaylward** [comment]
ok, I think I found it. Looks like I was missing Elastic.Apm.NLog . I had thought that Elastic.CommonSchema.NLog pulled it in, but it looks like it doesn't. Maybe something to note in the documentation when using ECS.

**Comment by snakefoot** [comment]
Updated example in original post to reflect your learned experiences.

**Comment by johnjaylward** [comment]
Looking at the message it generated, I guess I have a few comments/questions:
1. Why is `log.level` a top level field instead of being under the `log` object
1. I don't see any use of `${callsite}` or `${callsite-linenumber}` in the output. Is that configurable? I'd prefer to see those under `log.origin.function` and `log.origin.file.line` respectively assuming they are available at runtime.
1. As part of the "process" information, I'd like to be able to output the assembly version information so I can track errors that may have happened due to an upgrade. Before I found this PR, I was planning on putting it under the existing `package.version` field since the "process" object didn't seem to have version info. Can that be configured?
1. For some reason the `log.logger` shows as "Elastic.CommonSchema.NLog" instead of my logger name (i.e. "my.namespace.MyClass"). This seems unexpected. I don't really care what the logging system was that sent the log to Elastic, I care about the system generating the log.

Maybe these comments would be better placed in the "Elastic.CommonSchema.NLog" project?

**Comment by snakefoot** [comment]
> Maybe these comments would be better placed in the "Elastic.CommonSchema.NLog" project?

That would probably be best, since nothing can be done about them here. Small comments:

2. You can add your own custom attributes like this:
```xml
<layout type="EcsLayout">
    <metadata name="CallSite" layout="${callsite}" />
</layout>
```

3. Think that [Process](https://www.elastic.co/guide/en/ecs/current/ecs-process.html) and [service](https://www.elastic.co/guide/en/ecs/current/ecs-service.html) (Has Version) should be merged together. But it is not me making the rules.

4. This has been fixed with: https://github.com/elastic/ecs-dotnet/pull/67

But besides those comments, then data arrives as expected in ElasticSearch ?

**Comment by snakefoot** [comment]
@johnjaylward Note that you can also use the NLog JsonLayout and built your own favorite structure (Instead of EcsLayout):

https://github.com/nlog/nlog/wiki/JsonLayout

**Comment by johnjaylward** [comment]
> But besides those comments, then data arrives as expected in ElasticSearch ?

Yes, it looks like it worked well once I got that fixed. I think if the Elastic.CommonSchema.NLog group is going to use those fields though, they aught to include the `Elastic.Apm.NLog` package in their NuGet dependency list. I'll bring that up over there as well. If I'm not using it directly, then I shouldn't have to worry about it.

**Comment by snakefoot** [comment]
Thank you for the testing and fast feedback.

**Pull request merged**
