### PR TITLE
feat: Added option OpCodeCreate to support Elastic data streams

### LINKED ISSUE #132: Writing to data stream in elastic returns an error
Hello,

I set up my index to be a data stream in elastic but I get an error stating the request should have op_type: create.

Is there a way to overcome, or is this not ready yet to work with data streams?

Thank you

### PR DESCRIPTION
**Pull request by snakefoot**
Trying to resolve #132

#### Checklist
- [x] My commits follow [Conventional Commits](https://www.conventionalcommits.org)
- [ ] documentation is updated

### CODE REVIEW

**Comment by snakefoot** [comment]
@markmcdowell Ready for review, and @TheDruidsKeeper has [confirmed](https://github.com/markmcdowell/NLog.Targets.ElasticSearch/issues/132#issuecomment-726409436) the pre-release is working with data-streams in Elastic 7.9.

**Review by markmcdowell — APPROVED** [review]

**Comment by snakefoot** [comment]
Updated wiki for ver. 7.5.0 - https://github.com/markmcdowell/NLog.Targets.ElasticSearch/wiki

**Comment by snakefoot** [comment]
@markmcdowell Maybe update release-notes about the new setting opCodeCreate=true required for datastream-support:

https://github.com/markmcdowell/NLog.Targets.ElasticSearch/releases/tag/v7.5.0

Also the nuget-package seems to be pending:

https://www.nuget.org/packages/NLog.Targets.ElasticSearch

**Comment by markmcdowell** [comment]
Checking, looks like the nuget api key has expired.

**Comment by markmcdowell** [comment]
Ok api key updated, package published and release notes updated.

**Comment by snakefoot** [comment]
Excellent. You deserve a beer at the friday bar :)

**Pull request merged**
